import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import Link from "next/link";

export default function Home({ props }) {
  const { user, error, isLoading } = useUser();

  return (
    <>
      <Head>
        <title>Workout Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          {user ? (
            <div>
              <h1 className="text-3xl font-bold underline">Homepage</h1>
              <h2 className="text-2xl font-bold underline">
                Welcome {user.name}
              </h2>

              <Link href="/api/auth/logout">Logout</Link>
            </div>
          ) : (
            <div>
              <h1 className="text-3xl font-bold underline">Homepage</h1>
              <h2 className="text-2xl font-bold underline">Welcome Guest</h2>
              <Link href="/api/auth/login">Login</Link>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
